name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.15.2'
          host: 'linux'
          target: 'desktop'
          arch: 'linux64_gcc'
          dir: '${{ github.workspace }}/qt'

      - name: Configure and Build with qmake
        run: |
          cd ${{ github.workspace }}
          mkdir build
          cd build
          qmake ..
          make

      - name: Run Tests
        run: cd ${{ github.workspace }}/build && make test
